# Generated by Django 6.0.2 on 2026-03-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stars',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
