# Generated by Django 6.0.2 on 2026-05-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recovery_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
