# Generated by Django 6.0.2 on 2026-03-28 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergameprofile',
            name='best_score',
        ),
        migrations.RemoveField(
            model_name='usergameprofile',
            name='stars',
        ),
        migrations.RemoveField(
            model_name='usergameprofile',
            name='total_correct',
        ),
        migrations.RemoveField(
            model_name='usergameprofile',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='usergameprofile',
            name='total_stars',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DailyKeyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('used_keys', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_key_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
