# Generated by Django 6.0.2 on 2026-03-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_usergameprofile_best_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergameprofile',
            name='best_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usergameprofile',
            name='total_correct',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
