# Generated by Django 6.0.2 on 2026-03-28 05:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usergameprofile_best_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergameprofile',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='usergameprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergameprofile',
            name='keys_updated_at',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='usergameprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='usergameprofile',
            name='remaining_keys',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='usergameprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='DailyKeyUsage',
        ),
    ]
