# Generated by Django 6.0.2 on 2026-03-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_usergameprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergameprofile',
            name='nickname_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
