# Generated by Django 6.0.2 on 2026-04-30 13:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usergameprofile_nickname_changed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=500, null=True)),
                ('visit_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['visit_date'], name='core_visito_visit_d_2498a4_idx'), models.Index(fields=['ip_address'], name='core_visito_ip_addr_b354f5_idx')],
                'unique_together': {('ip_address', 'visit_date')},
            },
        ),
    ]
