# Generated by Django 6.0.2 on 2026-04-30 13:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_visitorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('path', models.CharField(max_length=500)),
                ('visit_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['path'], name='core_pagevi_path_fcf89f_idx'), models.Index(fields=['visit_date'], name='core_pagevi_visit_d_354a7a_idx'), models.Index(fields=['created_at'], name='core_pagevi_created_4fd89e_idx')],
            },
        ),
    ]
