# Generated by Django 6.0.2 on 2026-05-01 08:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pageviewlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('game_start', 'Game Start'), ('game_finish', 'Game Finish'), ('login_click', 'Login Click'), ('signup', 'Signup')], max_length=50)),
                ('game_name', models.CharField(blank=True, default='', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('path', models.CharField(blank=True, default='', max_length=500)),
                ('session_key', models.CharField(blank=True, default='', max_length=80)),
                ('score', models.PositiveIntegerField(default=0)),
                ('correct', models.PositiveIntegerField(default=0)),
                ('gained_stars', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(blank=True, default='', max_length=100)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('event_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_event_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['event_type'], name='core_gameev_event_t_8daec0_idx'), models.Index(fields=['game_name'], name='core_gameev_game_na_f9413f_idx'), models.Index(fields=['event_date'], name='core_gameev_event_d_ebc3c2_idx'), models.Index(fields=['created_at'], name='core_gameev_created_f440e2_idx')],
            },
        ),
    ]
