"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv


BASE_DIR = Path(__file__).resolve().parent.parent

# .env 로드
load_dotenv(BASE_DIR / ".env")


# =========================
# Helper
# =========================
def env_bool(name, default=False):
    value = os.getenv(name)

    if value is None:
        return default

    return str(value).strip().lower() in ("1", "true", "yes", "y", "on")


# =========================
# Core
# =========================
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise ValueError("SECRET_KEY is not set in .env")

DEBUG = os.getenv("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "ALLOWED_HOSTS",
        "127.0.0.1,localhost,mathner.com,www.mathner.com"
    ).split(",")
    if host.strip()
]


# =========================
# Application definition
# =========================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.sitemaps",

    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",

    "apps.core.apps.CoreConfig",
    "apps.accounts",
    "apps.game",
    "apps.rewards",
    "apps.ranking",
    "apps.social",
    "apps.avatar",
    "apps.shop",
    "apps.billing",
    "apps.support",
    "apps.community",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "apps.core.middleware.VisitorTrackingMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "config.middleware.SimplePerfMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.core.context_processors.profile_context",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# =========================
# Database
# =========================
DATABASE_URL = os.getenv("DATABASE_URL")
if not DATABASE_URL:
    raise ValueError("DATABASE_URL is not set in .env")

DATABASES = {
    "default": dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,
        ssl_require=not DEBUG,
    )
}


# =========================
# Password validation
# =========================
# 매스너는 아이들이 외우기 쉬운 6자리 PIN 로그인을 사용하므로
# Django 기본 비밀번호 검사기는 비활성화합니다.
# 실제 PIN 형식 검사는 apps.accounts.forms.MathnerSignupForm 에서 처리합니다.
AUTH_PASSWORD_VALIDATORS = []


# =========================
# Internationalization
# =========================
LANGUAGE_CODE = "ko-kr"
TIME_ZONE = "Asia/Seoul"

USE_I18N = True
USE_TZ = True


# =========================
# Static files / Media
# =========================
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# =========================
# Default primary key field type
# =========================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# =========================
# django sites
# =========================
SITE_ID = int(os.getenv("SITE_ID", "1"))


# =========================
# Login / Logout
# =========================
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/play/"
LOGOUT_REDIRECT_URL = "/"


# =========================
# Authentication backends
# =========================
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]


# =========================
# allauth
# =========================
# 로그인 방식:
# - 구글 로그인 유지
# - 자체 로그인은 이메일이 아니라 "매스너 아이디 + 6자리 PIN" 사용
ACCOUNT_LOGIN_METHODS = {"username"}

# 회원가입 필드:
# - username: 매스너 아이디
# - email: 보호자 복구 이메일
# - password1/password2: 6자리 PIN
ACCOUNT_SIGNUP_FIELDS = ["username*", "email*", "password1*", "password2*"]

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "none"

# 비밀번호/PIN 찾기 활성화
# allauth 기본 password reset URL:
# /accounts/password/reset/
# 이 기능은 User.email 기준으로 재설정 메일을 보냅니다.
ACCOUNT_EMAIL_UNKNOWN_ACCOUNTS = False
ACCOUNT_CHANGE_EMAIL = True

SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_AUTO_SIGNUP = True

ACCOUNT_SESSION_REMEMBER = None

ACCOUNT_FORMS = {
    "login": "apps.accounts.forms.MathnerLoginForm",
    "signup": "apps.accounts.forms.MathnerSignupForm",
}

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {
            "prompt": "select_account",
            "access_type": "online",
        },
        "EMAIL_AUTHENTICATION": True,
        "EMAIL_AUTHENTICATION_AUTO_CONNECT": True,
    }
}


# =========================
# Session / Cookie
# =========================
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False

SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"


# =========================
# CSRF / Security
# =========================
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CSRF_TRUSTED_ORIGINS",
        "https://mathner.com,https://www.mathner.com,http://localhost:8000,http://127.0.0.1:8000"
    ).split(",")
    if origin.strip()
]

if DEBUG:
    SECURE_PROXY_SSL_HEADER = None
else:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SECURE_SSL_REDIRECT = env_bool(
    "SECURE_SSL_REDIRECT",
    False if DEBUG else True
)

SESSION_COOKIE_SECURE = env_bool(
    "SESSION_COOKIE_SECURE",
    False if DEBUG else True
)

CSRF_COOKIE_SECURE = env_bool(
    "CSRF_COOKIE_SECURE",
    False if DEBUG else True
)

SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"

SECURE_HSTS_SECONDS = int(
    os.getenv(
        "SECURE_HSTS_SECONDS",
        "0" if DEBUG else "31536000"
    )
)

SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    "SECURE_HSTS_INCLUDE_SUBDOMAINS",
    False if DEBUG else True
)

SECURE_HSTS_PRELOAD = env_bool(
    "SECURE_HSTS_PRELOAD",
    False if DEBUG else True
)


# =========================
# Admin security helper
# =========================
ADMIN_URL = os.getenv("ADMIN_URL", "admin/")


# =========================
# GeoIP optional
# =========================
GEOIP_PATH = BASE_DIR / "geoip"


# =========================
# Email / Password Reset
# =========================
# 로컬 기본값:
# - 실제 메일 발송 X
# - 개발 서버 터미널에 재설정 링크 출력
#
# 운영 서버에서 실제 메일 발송하려면 .env에 아래 값을 넣으세요.
# EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
# EMAIL_HOST=smtp.gmail.com
# EMAIL_PORT=587
# EMAIL_USE_TLS=True
# EMAIL_HOST_USER=your_email@gmail.com
# EMAIL_HOST_PASSWORD=google_app_password
# DEFAULT_FROM_EMAIL=Mathner <your_email@gmail.com>

EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend"
)

EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", True)
EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", False)

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")

DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    "Mathner <noreply@mathner.com>"
)

SERVER_EMAIL = os.getenv(
    "SERVER_EMAIL",
    DEFAULT_FROM_EMAIL
)

# 비밀번호/PIN 재설정 링크 유효시간
# 기본 1시간
PASSWORD_RESET_TIMEOUT = int(os.getenv("PASSWORD_RESET_TIMEOUT", str(60 * 60)))


# =========================
# Logging
# =========================
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
}


# =========================
# Redis Cache
# =========================
USE_REDIS = os.getenv("USE_REDIS", "False").lower() == "true"

if USE_REDIS:
    REDIS_CACHE_URL = os.getenv("REDIS_CACHE_URL", "redis://127.0.0.1:6379/1")

    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_CACHE_URL,
            "TIMEOUT": 300,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }


# =========================
# Celery
# =========================
if USE_REDIS:
    CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://127.0.0.1:6379/2")
    CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://127.0.0.1:6379/2")

    CELERY_ACCEPT_CONTENT = ["json"]
    CELERY_TASK_SERIALIZER = "json"
    CELERY_RESULT_SERIALIZER = "json"
    CELERY_TIMEZONE = TIME_ZONE
else:
    CELERY_TASK_ALWAYS_EAGER = True