# Generated by Django 6.0.2 on 2026-04-05 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_display', models.CharField(blank=True, max_length=150)),
                ('email_snapshot', models.EmailField(blank=True, max_length=254)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('progress', 'In Progress'), ('done', 'Done')], default='new', max_length=20)),
                ('admin_memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '1:1 Inquiry',
                'verbose_name_plural': '1:1 Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
