# Generated by Django 6.0.2 on 2026-04-04 01:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_mode', models.CharField(choices=[('practice', 'Practice'), ('classic', 'Classic'), ('challenge', 'Challenge')], default='practice', max_length=20)),
                ('operation', models.CharField(choices=[('add', 'Add'), ('sub', 'Subtract'), ('mul', 'Multiply'), ('div', 'Divide'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('score', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('earned_stars', models.PositiveIntegerField(default=0)),
                ('best_combo', models.PositiveIntegerField(default=0)),
                ('played_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', '-played_at'],
            },
        ),
        migrations.CreateModel(
            name='RankingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friends', models.ManyToManyField(blank=True, related_name='rank_friends', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
