# Generated by Django 6.0.2 on 2026-04-04 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamescore',
            options={'ordering': ['-played_at', '-correct_count', '-best_combo', '-earned_stars']},
        ),
    ]
