# Generated by Django 6.0.2 on 2026-04-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_alter_gamescore_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='game_mode',
            field=models.CharField(choices=[('practice', 'Practice'), ('classic', 'Classic'), ('challenge', 'Challenge'), ('avatar_aura', 'Avatar Aura'), ('acid_rain', 'Acid Rain'), ('tug_of_war', 'Tug of War')], default='practice', max_length=20),
        ),
    ]
