# Generated by Django 6.0.3 on 2026-04-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_alter_gamescore_game_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='game_mode',
            field=models.CharField(choices=[('practice', 'Practice'), ('classic', 'Classic'), ('challenge', 'Challenge'), ('avatar_aura', 'Avatar Aura'), ('math_rain', 'Math Rain'), ('tug_of_war', 'Tug of War')], default='practice', max_length=20),
        ),
    ]
