# Generated by Django 6.0.2 on 2026-03-28 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('avatar_hair', 'Avatar Hair'), ('avatar_top', 'Avatar Top'), ('avatar_bottom', 'Avatar Bottom'), ('avatar_shoes', 'Avatar Shoes'), ('avatar_hat', 'Avatar Hat'), ('avatar_accessory', 'Avatar Accessory'), ('room_wallpaper', 'Room Wallpaper'), ('room_floor', 'Room Floor'), ('room_furniture', 'Room Furniture'), ('room_decoration', 'Room Decoration')], max_length=30)),
                ('sub_category', models.CharField(blank=True, max_length=50)),
                ('price_stars', models.PositiveIntegerField(default=0)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='shop/thumbnails/')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='shop/previews/')),
                ('asset_key', models.CharField(blank=True, help_text='Optional frontend asset key, e.g. avatar_top_school_01', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('is_limited', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('category', 'sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='UserOwnedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_by_users', to='shop.shopitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_shop_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
                'unique_together': {('user', 'item')},
            },
        ),
    ]
