# Generated by Django 6.0.2 on 2026-03-28 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userowneditem',
            options={'ordering': ('item__category', 'item__sort_order', 'id')},
        ),
        migrations.RenameField(
            model_name='userowneditem',
            old_name='purchased_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='shopitem',
            name='asset_key',
        ),
        migrations.RemoveField(
            model_name='shopitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shopitem',
            name='is_limited',
        ),
        migrations.RemoveField(
            model_name='shopitem',
            name='preview_image',
        ),
        migrations.RemoveField(
            model_name='shopitem',
            name='rarity',
        ),
        migrations.RemoveField(
            model_name='shopitem',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='shopitem',
            name='thumbnail_image',
        ),
        migrations.RemoveField(
            model_name='shopitem',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='shopitem',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='image_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='category',
            field=models.CharField(choices=[('avatar_top', 'Avatar Tops'), ('avatar_hat', 'Avatar Hats'), ('avatar_shoes', 'Avatar Shoes'), ('furniture', 'Furniture'), ('decoration', 'Decorations'), ('room_wallpaper', 'Wallpapers'), ('room_floor', 'Floors')], max_length=40),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='price_stars',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='slug',
            field=models.SlugField(max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='userowneditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_records', to='shop.shopitem'),
        ),
        migrations.AlterField(
            model_name='userowneditem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
