# Generated by Django 6.0.2 on 2026-03-28 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_userowneditem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userowneditem',
            options={},
        ),
        migrations.RemoveField(
            model_name='shopitem',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='shopitem',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='userowneditem',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='category',
            field=models.CharField(choices=[('avatar_cloth', 'Avatar Cloth'), ('avatar_hat', 'Avatar Hat'), ('avatar_shoes', 'Avatar Shoes'), ('furniture', 'Furniture'), ('decor', 'Decor')], max_length=40),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='price_stars',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userowneditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_users', to='shop.shopitem'),
        ),
    ]
