# Generated by Django 6.0.2 on 2026-04-05 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shopitem_options_alter_userowneditem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopitem',
            options={'ordering': ['category', 'gender', 'name']},
        ),
        migrations.AlterModelOptions(
            name='userowneditem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='shopitem',
            name='gender',
            field=models.CharField(choices=[('common', 'Common'), ('male', 'Male'), ('female', 'Female')], default='common', max_length=10),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='category',
            field=models.CharField(choices=[('avatar_face', 'Avatar Face'), ('avatar_hair', 'Avatar Hair'), ('avatar_body', 'Avatar Body'), ('avatar_top', 'Avatar Top'), ('avatar_cloth', 'Avatar Cloth'), ('avatar_pants', 'Avatar Pants'), ('avatar_shoes', 'Avatar Shoes'), ('avatar_hat', 'Avatar Hat'), ('furniture', 'Furniture'), ('decor', 'Decor')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userowneditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_by_users', to='shop.shopitem'),
        ),
        migrations.AlterField(
            model_name='userowneditem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
