# Generated by Django 6.0.2 on 2026-04-06 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_shopitem_options_alter_userowneditem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='font_family_key',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('gaegu', 'Gaegu'), ('dongle', 'Dongle'), ('gowun_batang', 'Gowun Batang'), ('nanum_pen', 'Nanum Pen Script'), ('dokdo', 'Dokdo')], default='', help_text='Used only when category is profile_font.', max_length=50),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='font_preview_text',
            field=models.CharField(blank=True, default='Nickname / Writing Preview', max_length=120),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='category',
            field=models.CharField(choices=[('avatar_face', 'Avatar Face'), ('avatar_hair', 'Avatar Hair'), ('avatar_body', 'Avatar Body'), ('avatar_top', 'Avatar Top'), ('avatar_cloth', 'Avatar Cloth'), ('avatar_pants', 'Avatar Pants'), ('avatar_shoes', 'Avatar Shoes'), ('avatar_hat', 'Avatar Hat'), ('furniture', 'Furniture'), ('decor', 'Decor'), ('profile_font', 'Profile Font')], max_length=30),
        ),
        migrations.CreateModel(
            name='UserFontPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nickname_font_item', models.ForeignKey(blank=True, limit_choices_to={'category': 'profile_font'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nickname_font_users', to='shop.shopitem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='font_preference', to=settings.AUTH_USER_MODEL)),
                ('writing_font_item', models.ForeignKey(blank=True, limit_choices_to={'category': 'profile_font'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writing_font_users', to='shop.shopitem')),
            ],
        ),
    ]
