# Generated by Django 6.0.2 on 2026-04-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shopitem_font_family_key_shopitem_font_preview_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfontpreference',
            name='nickname_effect_key',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('neon_blue', 'Neon Blue'), ('rainbow_flow', 'Rainbow Flow'), ('gold_glow', 'Gold Glow'), ('shadow_pop', 'Shadow Pop')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='userfontpreference',
            name='writing_effect_key',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('neon_blue', 'Neon Blue'), ('rainbow_flow', 'Rainbow Flow'), ('gold_glow', 'Gold Glow'), ('shadow_pop', 'Shadow Pop')], default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='font_family_key',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('gaegu', 'Gaegu'), ('dongle', 'Dongle'), ('gowun_batang', 'Gowun Batang'), ('nanum_pen', 'Nanum Pen Script'), ('dokdo', 'Dokdo'), ('bubblegum_sans', 'Bubblegum Sans'), ('delius_swash_caps', 'Delius Swash Caps'), ('boogaloo', 'Boogaloo'), ('love_ya_like_a_sister', 'Love Ya Like A Sister'), ('luckiest_guy', 'Luckiest Guy'), ('coming_soon', 'Coming Soon'), ('life_savers', 'Life Savers'), ('chewy', 'Chewy'), ('cabin_sketch', 'Cabin Sketch'), ('mouse_memoirs', 'Mouse Memoirs'), ('londrina_shadow', 'Londrina Shadow'), ('modak', 'Modak'), ('amatic_sc', 'Amatic SC'), ('capriola', 'Capriola'), ('mclaren', 'McLaren')], default='', help_text='Used only when category is profile_font.', max_length=50),
        ),
    ]
