# Generated by Django 6.0.2 on 2026-04-11 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_userfontpreference_nickname_effect_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfontpreference',
            name='nickname_effect_key',
        ),
        migrations.RemoveField(
            model_name='userfontpreference',
            name='writing_effect_key',
        ),
        migrations.RemoveField(
            model_name='userfontpreference',
            name='writing_font_item',
        ),
        migrations.AddField(
            model_name='userfontpreference',
            name='content_font_item',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'profile_font'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_font_users', to='shop.shopitem'),
        ),
        migrations.AddField(
            model_name='userfontpreference',
            name='title_font_item',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'profile_font'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title_font_users', to='shop.shopitem'),
        ),
    ]
