# Generated by Django 6.0.2 on 2026-04-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_userfontpreference_nickname_effect_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfontpreference',
            name='content_color',
            field=models.CharField(default='#eef4ff', max_length=20),
        ),
        migrations.AddField(
            model_name='userfontpreference',
            name='content_effect_key',
            field=models.CharField(choices=[('none', 'None'), ('neon_blue', 'Neon Blue'), ('rainbow_flow', 'Rainbow Flow'), ('gold_glow', 'Gold Glow'), ('sparkle', 'Sparkle'), ('glitch', 'Glitch'), ('float_wave', 'Float Wave'), ('fire_glow', 'Fire Glow'), ('ice_glow', 'Ice Glow')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='userfontpreference',
            name='nickname_color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
        migrations.AddField(
            model_name='userfontpreference',
            name='nickname_effect_key',
            field=models.CharField(choices=[('none', 'None'), ('neon_blue', 'Neon Blue'), ('rainbow_flow', 'Rainbow Flow'), ('gold_glow', 'Gold Glow'), ('sparkle', 'Sparkle'), ('glitch', 'Glitch'), ('float_wave', 'Float Wave'), ('fire_glow', 'Fire Glow'), ('ice_glow', 'Ice Glow')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='userfontpreference',
            name='nickname_letter_spacing',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userfontpreference',
            name='nickname_scale',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='userfontpreference',
            name='title_color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
        migrations.AddField(
            model_name='userfontpreference',
            name='title_effect_key',
            field=models.CharField(choices=[('none', 'None'), ('neon_blue', 'Neon Blue'), ('rainbow_flow', 'Rainbow Flow'), ('gold_glow', 'Gold Glow'), ('sparkle', 'Sparkle'), ('glitch', 'Glitch'), ('float_wave', 'Float Wave'), ('fire_glow', 'Fire Glow'), ('ice_glow', 'Ice Glow')], default='none', max_length=30),
        ),
    ]
