# Generated by Django 6.0.2 on 2026-04-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_userownedeffect'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='effect_key',
            field=models.CharField(blank=True, default='', help_text='Used only when category is profile_effect.', max_length=50),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='effect_preview_class',
            field=models.CharField(blank=True, default='', help_text='Used only when category is profile_effect.', max_length=100),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='category',
            field=models.CharField(choices=[('avatar_face', 'Avatar Face'), ('avatar_hair', 'Avatar Hair'), ('avatar_body', 'Avatar Body'), ('avatar_top', 'Avatar Top'), ('avatar_cloth', 'Avatar Cloth'), ('avatar_pants', 'Avatar Pants'), ('avatar_shoes', 'Avatar Shoes'), ('avatar_hat', 'Avatar Hat'), ('furniture', 'Furniture'), ('decor', 'Decor'), ('profile_font', 'Profile Font'), ('profile_effect', 'Profile Effect'), ('set', 'Set'), ('unique', 'Unique')], max_length=30),
        ),
    ]
