# Generated by Django 6.0.1 on 2026-04-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_shopitem_effect_key_shopitem_effect_preview_class_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopitem',
            options={'ordering': ['category', 'equip_slot', 'gender', 'name']},
        ),
        migrations.AddField(
            model_name='shopitem',
            name='equip_slot',
            field=models.CharField(blank=True, choices=[('', 'No slot'), ('head', 'Head'), ('eyes', 'Eyes'), ('mouth', 'Mouth'), ('eyebrow', 'Eyebrow'), ('front_hair', 'Front Hair'), ('rear_hair', 'Rear Hair'), ('body', 'Body'), ('top', 'Top'), ('cloth', 'Cloth'), ('pants', 'Pants'), ('shoes', 'Shoes'), ('hat', 'Hat')], default='', help_text='Avatar/Set/Unique item equip slot. Use Cloth, Pants, Shoes, Hat, etc.', max_length=30),
        ),
    ]
