# Generated by Django 6.0.2 on 2026-04-17 17:13

import apps.community.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_communitycomment_communitycommentlike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitycomment',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.RemoveField(
            model_name='communitypost',
            name='image',
        ),
        migrations.AddField(
            model_name='communitycomment',
            name='author_nickname_letter_spacing_snapshot',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='communitycomment',
            name='author_nickname_scale_snapshot',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='communitycomment',
            name='is_collapsed_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='author_nickname_letter_spacing_snapshot',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='author_nickname_scale_snapshot',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='communitycomment',
            name='author_font_key_snapshot',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='author_font_key_snapshot',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='CommunityPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.community.models.community_gallery_upload_to)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='community.communitypost')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
