# Generated by Django 6.0.2 on 2026-04-05 07:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_friendship_responded_at_alter_friendship_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomdiaryentry',
            options={'ordering': ('-entry_date', '-created_at')},
        ),
        migrations.AddField(
            model_name='roomdiaryentry',
            name='entry_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='roomdiaryentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='roomdiaryentry',
            unique_together={('user', 'entry_date')},
        ),
        migrations.CreateModel(
            name='RoomGuestbookReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_guestbook_replies', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social.roomguestbookentry')),
                ('room_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_guestbook_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
