# Generated by Django 6.0.2 on 2026-04-05 12:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_roomdiaryentry_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('entry_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuestbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuestbookReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_visits', models.PositiveIntegerField(default=0)),
                ('total_visits', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_token', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('visited_on', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='roomdiaryentry',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='roomdiaryentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='roomguestbookentry',
            name='author',
        ),
        migrations.RemoveField(
            model_name='roomguestbookentry',
            name='room_owner',
        ),
        migrations.RemoveField(
            model_name='roomguestbookreply',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='roomguestbookreply',
            name='author',
        ),
        migrations.RemoveField(
            model_name='roomguestbookreply',
            name='room_owner',
        ),
        migrations.AlterUniqueTogether(
            name='roomvisitlog',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='roomvisitlog',
            name='room_owner',
        ),
        migrations.RemoveField(
            model_name='roomvisitlog',
            name='visitor',
        ),
        migrations.AlterModelOptions(
            name='friendship',
            options={},
        ),
        migrations.AlterModelOptions(
            name='roomlike',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='roomlike',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='friendship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='roomlike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='roomlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['from_user', 'status'], name='social_frie_from_us_353929_idx'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['to_user', 'status'], name='social_frie_to_user_084357_idx'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['status', '-created_at'], name='social_frie_status_03bbf9_idx'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user'), name='uniq_friendship_from_to'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='friendship_no_self_link'),
        ),
        migrations.AddField(
            model_name='guestbookentry',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guestbook_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guestbookreply',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guestbook_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guestbookreply',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social.guestbookentry'),
        ),
        migrations.AddField(
            model_name='room',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guestbookentry',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guestbook_entries', to='social.room'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='social.room'),
        ),
        migrations.AddField(
            model_name='roomlike',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='social.room'),
        ),
        migrations.AddIndex(
            model_name='roomlike',
            index=models.Index(fields=['room', '-created_at'], name='social_room_room_id_960cd7_idx'),
        ),
        migrations.AddIndex(
            model_name='roomlike',
            index=models.Index(fields=['user', '-created_at'], name='social_room_user_id_d7aff8_idx'),
        ),
        migrations.AddConstraint(
            model_name='roomlike',
            constraint=models.UniqueConstraint(fields=('room', 'user'), name='uniq_room_like_room_user'),
        ),
        migrations.AddField(
            model_name='roomvisit',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='social.room'),
        ),
        migrations.AddField(
            model_name='roomvisit',
            name='viewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RoomDiaryEntry',
        ),
        migrations.DeleteModel(
            name='RoomGuestbookEntry',
        ),
        migrations.DeleteModel(
            name='RoomGuestbookReply',
        ),
        migrations.DeleteModel(
            name='RoomVisitLog',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='responded_at',
        ),
        migrations.RemoveField(
            model_name='roomlike',
            name='room_owner',
        ),
        migrations.AddIndex(
            model_name='guestbookreply',
            index=models.Index(fields=['entry', 'created_at'], name='social_gues_entry_i_b8409a_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['owner'], name='social_room_owner_i_c85923_idx'),
        ),
        migrations.AddIndex(
            model_name='guestbookentry',
            index=models.Index(fields=['room', '-created_at'], name='social_gues_room_id_c367fd_idx'),
        ),
        migrations.AddIndex(
            model_name='guestbookentry',
            index=models.Index(fields=['author', '-created_at'], name='social_gues_author__ccc654_idx'),
        ),
        migrations.AddIndex(
            model_name='diaryentry',
            index=models.Index(fields=['room', 'entry_date'], name='social_diar_room_id_10f8ee_idx'),
        ),
        migrations.AddIndex(
            model_name='diaryentry',
            index=models.Index(fields=['room', '-created_at'], name='social_diar_room_id_502188_idx'),
        ),
        migrations.AddConstraint(
            model_name='diaryentry',
            constraint=models.UniqueConstraint(fields=('room', 'entry_date'), name='uniq_room_entry_date'),
        ),
        migrations.AddIndex(
            model_name='roomvisit',
            index=models.Index(fields=['room', 'visited_on'], name='social_room_room_id_691ef5_idx'),
        ),
        migrations.AddIndex(
            model_name='roomvisit',
            index=models.Index(fields=['room', 'viewer', 'visited_on'], name='social_room_room_id_ed5054_idx'),
        ),
        migrations.AddIndex(
            model_name='roomvisit',
            index=models.Index(fields=['room', 'guest_token', 'visited_on'], name='social_room_room_id_ec6b64_idx'),
        ),
    ]
