# Generated by Django 6.0.2 on 2026-04-05 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_diaryentry_guestbookentry_guestbookreply_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='social.room'),
        ),
        migrations.AlterField(
            model_name='guestbookentry',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guestbook_entries', to='social.room'),
        ),
        migrations.AlterField(
            model_name='roomlike',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='social.room'),
        ),
        migrations.AlterField(
            model_name='roomvisit',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='social.room'),
        ),
    ]
