# Generated by Django 6.0.2 on 2026-04-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_diaryentry_room_alter_guestbookentry_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='content_effect_key',
            field=models.CharField(choices=[('none', 'None'), ('neon_blue', 'Neon Blue'), ('rainbow_flow', 'Rainbow Flow'), ('gold_glow', 'Gold Glow'), ('sparkle', 'Sparkle'), ('glitch', 'Glitch'), ('float_wave', 'Float Wave'), ('fire_glow', 'Fire Glow'), ('ice_glow', 'Ice Glow')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='content_font_key',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='title_effect_key',
            field=models.CharField(choices=[('none', 'None'), ('neon_blue', 'Neon Blue'), ('rainbow_flow', 'Rainbow Flow'), ('gold_glow', 'Gold Glow'), ('sparkle', 'Sparkle'), ('glitch', 'Glitch'), ('float_wave', 'Float Wave'), ('fire_glow', 'Fire Glow'), ('ice_glow', 'Ice Glow')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='title_font_key',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='guestbookentry',
            name='content_effect_key',
            field=models.CharField(choices=[('none', 'None'), ('neon_blue', 'Neon Blue'), ('rainbow_flow', 'Rainbow Flow'), ('gold_glow', 'Gold Glow'), ('sparkle', 'Sparkle'), ('glitch', 'Glitch'), ('float_wave', 'Float Wave'), ('fire_glow', 'Fire Glow'), ('ice_glow', 'Ice Glow')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='guestbookentry',
            name='content_font_key',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='guestbookentry',
            name='nickname_effect_key',
            field=models.CharField(choices=[('none', 'None'), ('neon_blue', 'Neon Blue'), ('rainbow_flow', 'Rainbow Flow'), ('gold_glow', 'Gold Glow'), ('sparkle', 'Sparkle'), ('glitch', 'Glitch'), ('float_wave', 'Float Wave'), ('fire_glow', 'Fire Glow'), ('ice_glow', 'Ice Glow')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='guestbookentry',
            name='nickname_font_key',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='guestbookentry',
            name='nickname_letter_spacing',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='guestbookentry',
            name='nickname_scale',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='guestbookreply',
            name='content_effect_key',
            field=models.CharField(choices=[('none', 'None'), ('neon_blue', 'Neon Blue'), ('rainbow_flow', 'Rainbow Flow'), ('gold_glow', 'Gold Glow'), ('sparkle', 'Sparkle'), ('glitch', 'Glitch'), ('float_wave', 'Float Wave'), ('fire_glow', 'Fire Glow'), ('ice_glow', 'Ice Glow')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='guestbookreply',
            name='content_font_key',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='guestbookreply',
            name='nickname_effect_key',
            field=models.CharField(choices=[('none', 'None'), ('neon_blue', 'Neon Blue'), ('rainbow_flow', 'Rainbow Flow'), ('gold_glow', 'Gold Glow'), ('sparkle', 'Sparkle'), ('glitch', 'Glitch'), ('float_wave', 'Float Wave'), ('fire_glow', 'Fire Glow'), ('ice_glow', 'Ice Glow')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='guestbookreply',
            name='nickname_font_key',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='guestbookreply',
            name='nickname_letter_spacing',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='guestbookreply',
            name='nickname_scale',
            field=models.FloatField(default=1.0),
        ),
    ]
