# Generated by Django 6.0.2 on 2026-04-18 22:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_diaryentry_content_effect_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_visit_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['last_visit_date'], name='social_room_last_vi_155887_idx'),
        ),
    ]
