# Generated by Django 6.0.2 on 2026-03-28 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvatarProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_tone', models.CharField(default='default', max_length=30)),
                ('hair_color', models.CharField(default='black', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accessory_item', models.ForeignKey(blank=True, limit_choices_to={'category': 'avatar_accessory'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_accessory', to='shop.shopitem')),
                ('bottom_item', models.ForeignKey(blank=True, limit_choices_to={'category': 'avatar_bottom'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_bottom', to='shop.shopitem')),
                ('hair_item', models.ForeignKey(blank=True, limit_choices_to={'category': 'avatar_hair'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_hair', to='shop.shopitem')),
                ('hat_item', models.ForeignKey(blank=True, limit_choices_to={'category': 'avatar_hat'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_hat', to='shop.shopitem')),
                ('shoes_item', models.ForeignKey(blank=True, limit_choices_to={'category': 'avatar_shoes'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_shoes', to='shop.shopitem')),
                ('top_item', models.ForeignKey(blank=True, limit_choices_to={'category': 'avatar_top'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_top', to='shop.shopitem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='UserRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(default='My Room', max_length=100)),
                ('room_width', models.PositiveIntegerField(default=1280)),
                ('room_height', models.PositiveIntegerField(default=720)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('background_item', models.ForeignKey(blank=True, limit_choices_to={'category': 'room_decoration'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_background', to='shop.shopitem')),
                ('floor_item', models.ForeignKey(blank=True, limit_choices_to={'category': 'room_floor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_floor', to='shop.shopitem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_profile', to=settings.AUTH_USER_MODEL)),
                ('wallpaper_item', models.ForeignKey(blank=True, limit_choices_to={'category': 'room_wallpaper'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_wallpaper', to='shop.shopitem')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='UserRoomPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('z_index', models.IntegerField(default=1)),
                ('rotation', models.IntegerField(default=0)),
                ('scale', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('placed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owned_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='shop.userowneditem')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='avatar.userroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_placements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('z_index', 'id'),
            },
        ),
    ]
