# Generated by Django 6.0.2 on 2026-03-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useravatarprofile',
            name='avatar_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=20),
        ),
        migrations.AddField(
            model_name='useravatarprofile',
            name='base_x',
            field=models.IntegerField(default=325),
        ),
        migrations.AddField(
            model_name='useravatarprofile',
            name='base_y',
            field=models.IntegerField(default=380),
        ),
        migrations.AddField(
            model_name='useravatarprofile',
            name='base_z_index',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='userroom',
            name='room_height',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='userroom',
            name='room_width',
            field=models.PositiveIntegerField(default=800),
        ),
    ]
