# Generated by Django 6.0.2 on 2026-03-28 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0002_useravatarprofile_avatar_gender_and_more'),
        ('shop', '0002_alter_userowneditem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatarprofile',
            name='accessory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_accessory', to='shop.shopitem'),
        ),
        migrations.AlterField(
            model_name='useravatarprofile',
            name='bottom_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_bottom', to='shop.shopitem'),
        ),
        migrations.AlterField(
            model_name='useravatarprofile',
            name='hair_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_hair', to='shop.shopitem'),
        ),
        migrations.AlterField(
            model_name='userroom',
            name='background_item',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'decoration'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_background', to='shop.shopitem'),
        ),
    ]
