# Generated by Django 6.0.2 on 2026-03-28 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0003_alter_useravatarprofile_accessory_item_and_more'),
        ('shop', '0003_alter_shopitem_options_alter_userowneditem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userroomplacement',
            name='room',
        ),
        migrations.RemoveField(
            model_name='userroomplacement',
            name='owned_item',
        ),
        migrations.RemoveField(
            model_name='userroomplacement',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='useravatarprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='useravatarprofile',
            name='accessory_item',
        ),
        migrations.RemoveField(
            model_name='useravatarprofile',
            name='avatar_gender',
        ),
        migrations.RemoveField(
            model_name='useravatarprofile',
            name='base_x',
        ),
        migrations.RemoveField(
            model_name='useravatarprofile',
            name='base_y',
        ),
        migrations.RemoveField(
            model_name='useravatarprofile',
            name='base_z_index',
        ),
        migrations.RemoveField(
            model_name='useravatarprofile',
            name='bottom_item',
        ),
        migrations.RemoveField(
            model_name='useravatarprofile',
            name='hair_color',
        ),
        migrations.RemoveField(
            model_name='useravatarprofile',
            name='hair_item',
        ),
        migrations.RemoveField(
            model_name='useravatarprofile',
            name='skin_tone',
        ),
        migrations.RemoveField(
            model_name='useravatarprofile',
            name='top_item',
        ),
        migrations.AddField(
            model_name='useravatarprofile',
            name='cloth_item',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'avatar_cloth'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_cloth_profiles', to='shop.shopitem'),
        ),
        migrations.AddField(
            model_name='useravatarprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='useravatarprofile',
            name='size',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AddField(
            model_name='useravatarprofile',
            name='x',
            field=models.PositiveIntegerField(default=325),
        ),
        migrations.AddField(
            model_name='useravatarprofile',
            name='y',
            field=models.PositiveIntegerField(default=380),
        ),
        migrations.AddField(
            model_name='useravatarprofile',
            name='z_index',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='useravatarprofile',
            name='hat_item',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'avatar_hat'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_hat_profiles', to='shop.shopitem'),
        ),
        migrations.AlterField(
            model_name='useravatarprofile',
            name='shoes_item',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'avatar_shoes'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_shoes_profiles', to='shop.shopitem'),
        ),
        migrations.CreateModel(
            name='RoomItemPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField(default=0)),
                ('y', models.PositiveIntegerField(default=0)),
                ('z_index', models.PositiveIntegerField(default=1)),
                ('rotation', models.IntegerField(default=0)),
                ('scale', models.FloatField(default=1.0)),
                ('placed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owned_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='shop.userowneditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_item_placements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['z_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserRoomProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_width', models.PositiveIntegerField(default=800)),
                ('room_height', models.PositiveIntegerField(default=600)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserRoom',
        ),
        migrations.DeleteModel(
            name='UserRoomPlacement',
        ),
    ]
