# Generated by Django 6.0.2 on 2026-03-29 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0004_remove_userroomplacement_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomitemplacement',
            name='offset_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomitemplacement',
            name='offset_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomitemplacement',
            name='parent_placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_placements', to='avatar.roomitemplacement'),
        ),
        migrations.AddField(
            model_name='roomitemplacement',
            name='placement_type',
            field=models.CharField(choices=[('floor', 'Floor'), ('surface', 'Surface'), ('wall', 'Wall')], default='floor', max_length=20),
        ),
        migrations.AddField(
            model_name='roomitemplacement',
            name='surface_slot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='roomitemplacement',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roomitemplacement',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roomitemplacement',
            name='z_index',
            field=models.IntegerField(default=1),
        ),
    ]
