# Generated by Django 6.0.2 on 2026-04-06 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0005_roomitemplacement_offset_x_and_more'),
        ('shop', '0004_alter_shopitem_options_alter_userowneditem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useravatarprofile',
            name='body_item',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('category__in', ['avatar_body', 'body'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_body_profiles', to='shop.shopitem'),
        ),
        migrations.AddField(
            model_name='useravatarprofile',
            name='eyebrow_item',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('category__in', ['avatar_eyebrow', 'eyebrow', 'eyebrows', 'brow'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_eyebrow_profiles', to='shop.shopitem'),
        ),
        migrations.AddField(
            model_name='useravatarprofile',
            name='eyes_item',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('category__in', ['avatar_eyes', 'eyes', 'eye'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_eyes_profiles', to='shop.shopitem'),
        ),
        migrations.AddField(
            model_name='useravatarprofile',
            name='front_hair_item',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('category__in', ['avatar_front_hair', 'front_hair', 'hair_front', 'fronthair'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_front_hair_profiles', to='shop.shopitem'),
        ),
        migrations.AddField(
            model_name='useravatarprofile',
            name='head_item',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('category__in', ['avatar_head', 'head', 'face'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_head_profiles', to='shop.shopitem'),
        ),
        migrations.AddField(
            model_name='useravatarprofile',
            name='mouth_item',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('category__in', ['avatar_mouth', 'mouth', 'lip', 'lips'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_mouth_profiles', to='shop.shopitem'),
        ),
        migrations.AddField(
            model_name='useravatarprofile',
            name='pants_item',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('category__in', ['avatar_pants', 'pants', 'bottom', 'bottoms'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_pants_profiles', to='shop.shopitem'),
        ),
        migrations.AddField(
            model_name='useravatarprofile',
            name='rear_hair_item',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('category__in', ['avatar_rear_hair', 'rear_hair', 'hair_back', 'hair_rear', 'rearhair'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_rear_hair_profiles', to='shop.shopitem'),
        ),
        migrations.AddField(
            model_name='useravatarprofile',
            name='top_item',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('category__in', ['avatar_top', 'top'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_top_profiles', to='shop.shopitem'),
        ),
        migrations.AlterField(
            model_name='useravatarprofile',
            name='cloth_item',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('category__in', ['avatar_cloth', 'cloth', 'clothes', 'outfit'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_cloth_profiles', to='shop.shopitem'),
        ),
        migrations.AlterField(
            model_name='useravatarprofile',
            name='hat_item',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('category__in', ['avatar_hat', 'hat', 'cap'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_hat_profiles', to='shop.shopitem'),
        ),
        migrations.AlterField(
            model_name='useravatarprofile',
            name='shoes_item',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('category__in', ['avatar_shoes', 'shoes', 'shoe'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_shoes_profiles', to='shop.shopitem'),
        ),
    ]
